"""MCP server instructions — generated for agent context.

Currently static; will be dynamically generated from ``_tool_registry``
in a future wave.
"""

_INSTRUCTIONS = (
    "AutoMedia — Automated Media Production Pipeline\n"
    "================================================\n"
    "\n"
    "50 MCP tools for topic selection, pipeline execution, project\n"
    "management, Omni Triad document processing, brand strategy,\n"
    "cron schedule management, content quality evaluation,\n"
    "override management, and server health.\n"
    "\n"
    "━━━ CORE WORKFLOW (5 tools) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "Standard production pipeline (execute in order):\n"
    "\n"
    "  Step 1  select_topic(category?, tenant_id?)\n"
    "          Pick the highest-scored pending topic from the pool.\n"
    "          Returns {selected, remaining_count}. If null, add topics first.\n"
    "\n"
    "  Step 2  run_pipeline(topic, brand, mode?, resume_from?)\n"
    "          Launch the full production pipeline in a background thread.\n"
    "          Returns {project_id, status: 'started'} immediately.\n"
    "          Use the project_id to poll progress.\n"
    "\n"
    "  Step 3  get_pipeline_progress(project_id)\n"
    "          Poll gate-by-gate progress. Returns {current_gate, events[], error}.\n"
    "          Events include 'start', 'passed', 'failed' per gate.\n"
    "          Keep polling until all gates finish or an error appears.\n"
    "\n"
    "  Step 4  get_pipeline_status(project_id, base_dir?)\n"
    "          After completion, inspect the project's metadata and subdirectories.\n"
    "\n"
    "  Step 5  get_project_assets(project_dir)\n"
    "          List all generated files (MP4, SRT, cover images, drafts, etc.).\n"
    "\n"
    "  Step 6  list_projects(base_dir?, status?)\n"
    "          Browse all projects, optionally filtered by status.\n"
    "\n"
    "  Step 7  archive_project(project_id, base_dir?, force?)\n"
    "          Archive a completed project. SEE RED LINE 8 BELOW.\n"
    "\n"
    "━━━ PIPELINE MODES ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "  auto        Full pipeline: copy gates (G0-G5) + video gates (V0-V7)\n"
    "              + lifecycle gates (L1-L4).\n"
    "              Use for complete end-to-end production.\n"
    "\n"
    "  text_only   Copy gates only (G0-G5 + L1-L4). Skips video/audio.\n"
    "              Use when you only need a written article or social post.\n"
    "\n"
    "  text_with_cover  Copy gates (G0-G5 + L1-L4) + single cover image.\n"
    "              Generates a cover image in 02_images/cover/.\n"
    "\n"
    "  video_only  Video gates only (V0-V7 + L1-L4). Assumes text already exists.\n"
    "              Use when the draft is ready and you only need video output.\n"
    "\n"
    "  qa_only     Quality-assurance pass — runs selected QA gates on existing\n"
    "              content without generating new assets. Use for re-validation.\n"
    "\n"
    "━━━ STRATEGY & CONTENT QUALITY (4 tools) ━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "  run_brand_strategy(brand_name, industry, target_audience, context?)\n"
    "      Generate a brand strategy using LLM-driven analysis.\n"
    "      Returns {brand_positioning, audience_analysis,\n"
    "      competitive_landscape, key_differentiators, suggested_messaging}.\n"
    "\n"
    "  run_pipeline_from_strategy(topic, brand, mode?, strategy_context?)\n"
    "      Generate a content strategy via LLM then execute the pipeline.\n"
    "      Returns {strategy: {...}, pipeline_result: {...}}.\n"
    "\n"
    "  research_topics(category, count?, trending?)\n"
    "      Research trending/high-potential topics using LLM.\n"
    "      Returns structured list with angles, confidence scores, and\n"
    "      format recommendations.\n"
    "\n"
    "  evaluate_content_quality(content, criteria?, brand?)\n"
    "      Score content against specified criteria using LLM evaluation.\n"
    "      Returns {quality_score, issues[], suggestions[], overall_assessment}.\n"
    "\n"
    "━━━ OMNI TRIAD TOOLS (4 tools) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "Document processing pipeline (extract → translate → convert):\n"
    "\n"
    "  extract_brief(file_path, source_lang?, target_lang?)\n"
    "      Extract structured markdown + manifest JSON from a document (PDF, DOCX…).\n"
    "      Returns {md_content, manifest_json, warnings}.\n"
    "\n"
    "  localize_content(md_content, source_lang, target_lang)\n"
    "      Translate markdown text via OL shield → LLM → repair → unshield pipeline.\n"
    "      Returns {translated_md, xliff_path?, warnings}.\n"
    "\n"
    "  localize_output(project_dir, target_langs)\n"
    "      Batch-translate all drafts in a project into multiple languages.\n"
    "      target_langs is comma-separated (e.g. 'en,ja,ko').\n"
    "      Reads from 01_content/drafts/, writes to 05_publish/{lang}/.\n"
    "\n"
    "  format_output(content, target_format)\n"
    "      Convert markdown to another format. Supported: html, pdf, docx, md.\n"
    "      Returns {output_path, output_format, warnings}.\n"
    "\n"
    "━━━ TOPIC POOL (2 tools) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "  list_topic_pool(status?, category?, pool_db_path?)\n"
    "      List topics with optional filters. Use to browse available topics\n"
    "      before calling select_topic.\n"
    "\n"
    "  register_platform_adapter(platform_name, adapter_class?)\n"
    "      Register a publish adapter. STUB — returns instructions for future use.\n"
    "\n"
    "━━━ SERVER (1 tool) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "  health_check()\n"
    "      Returns {status, version, uptime_s, tools_count}. No parameters.\n"
    "\n"
    "━━━ BRAND TOOLS (1 tool) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "  list_brands()\n"
    "      List all configured brands with full profile metadata.\n"
    "      Returns structured list with aliases, CTA principles, blocked\n"
    "      words, tone guidelines, brand identity, languages, industry,\n"
    "      target audience, personality, and platforms.\n"
    "\n"
    "━━━ CRON SCHEDULE TOOLS (3 tools) ━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "  add_cron_schedule(name, expression, brand?, category?, count?)\n"
    "      Add a cron schedule entry to cron/jobs.yaml. Validates\n"
    "      the cron expression (5 fields) and prevents duplicate names.\n"
    "      Returns {added: true, name} on success.\n"
    "\n"
    "  list_cron_schedules()\n"
    "      List all cron schedule entries sorted by name.\n"
    "      Returns {schedules[], count}.\n"
    "\n"
    "  remove_cron_schedule(name)\n"
    "      Remove a cron schedule entry by name.\n"
    "      Returns {removed: true, name} or {error} if not found.\n"
    "\n"
    "━━━ ACCOUNT TOOLS (4 tools) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "  connect_account(platform, auth_type?, credentials?, label?)\n"
    "      Register a new platform account for publishing.\n"
    "      Returns {account_id, platform, status}.\n"
    "\n"
    "  list_accounts(platform?, status?)\n"
    "      List all registered accounts with optional filters.\n"
    "      Returns {accounts[], count}.\n"
    "\n"
    "  get_account_health(account_id)\n"
    "      Check an account's session health.\n"
    "      Returns {account_id, platform, status, last_health_check}.\n"
    "\n"
    "  disconnect_account(account_id)\n"
    "      Remove a platform account.\n"
    "      Returns {success, account_id, platform}.\n"
    "\n"
    "━━━ ERROR HANDLING ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "All tools return JSON dicts. On error the dict contains an 'error' key:\n"
    '  {"error": "description of what went wrong"}\n'
    "\n"
    "Common error patterns:\n"
    "  - 'path not allowed' — file outside the allowlist. Configure\n"
    "    allowed_directories in mcp_allowlist.yaml.\n"
    "  - 'No pending topics found' — topic pool is empty. Add topics first.\n"
    "  - 'No active pipeline found' — invalid project_id or pipeline finished.\n"
    "  - Gate failures show the gate name (G0, V3, etc.) and failure details.\n"
    "    See the gate info resource: automedia://gate/{gate_name}/info\n"
    "\n"
    "━━━ RED LINES (MUST OBEY) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "Red Line 8 — Archive Protection:\n"
    "  archive_project refuses unless project status is 'published' OR force=True.\n"
    "  Agents MUST NOT set force=True without explicit user instruction.\n"
    "  Only the user may force-archive a non-published project.\n"
    "\n"
    "Path Allowlist:\n"
    "  All file-path tool parameters are checked against mcp_allowlist.yaml.\n"
    "  Empty allowed_directories = deny all paths. Modify the YAML to permit\n"
    "  access to your project directories. Do NOT modify without user request.\n"
    "\n"
    "━━━ HITL & DIRECTOR MODE APPROVAL ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "Certain gates may pause for human review (HITL). When a gate enters\n"
    "HITL state, the pipeline waits for human approval via the CLI:\n"
    "  automedia hitl approve <project_id> <gate_name>\n"
    "  automedia hitl reject <project_id> <gate_name>\n"
    "\n"
    "When director mode is enabled (pause_on_approval=True), gates with\n"
    "requires_approval in their context pause for MCP-level approval:\n"
    "  get_pending_approvals(project_id?)  → list waiting gates\n"
    "  approve_gate(project_id, gate_name)   → approve and resume\n"
    "  reject_gate(project_id, gate_name)    → reject and resume\n"
    "\n"
    "Use get_pipeline_progress to detect paused gates (status:\n"
    "'awaiting_hitl' with detail 'awaiting_approval'), then call\n"
    "approve_gate or reject_gate to continue pipeline execution.\n"
    "\n"
    "━━━ EXAMPLE MULTI-STEP WORKFLOWS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n"
    "\n"
    "Workflow A — Full production from topic pool:\n"
    "  1. select_topic(category='tech')        → get topic\n"
    "  2. run_pipeline(topic, brand, 'auto')    → get project_id\n"
    "  3. get_pipeline_progress(project_id)     → poll until done\n"
    "  4. get_project_assets(project_dir)       → list outputs\n"
    "  5. archive_project(project_id)           → clean up\n"
    "\n"
    "Workflow B — Text-only article:\n"
    "  1. run_pipeline('AI trends', 'my-brand', 'text_only')\n"
    "  2. get_pipeline_progress(project_id) until all gates pass\n"
    "  3. get_project_assets(project_dir) to get the draft\n"
    "\n"
    "Workflow C — Extract and translate a document:\n"
    "  1. extract_brief('/path/to/source.pdf')   → get md_content\n"
    "  2. localize_content(md_content, 'zh', 'en') → translate\n"
    "  3. format_output(translated_md, 'html')    → convert to HTML\n"
    "\n"
    "Workflow D — Multi-language localization:\n"
    "  1. localize_output(project_dir, 'en,ja,ko')\n"
    "     → translates all drafts into 3 languages at once\n"
)


def get_instructions() -> str:
    """Return the MCP server instructions string.

    Currently static; will be dynamically generated from ``_tool_registry``
    in a future wave.
    """
    return _INSTRUCTIONS
