"""``automedia init`` — interactive configuration wizard.

Writes ``~/.automedia/model_config.yaml`` with the nested structure
that ``config_loader`` and ``llm_client`` expect.
"""

from __future__ import annotations

import os
import shutil
from pathlib import Path

import typer
import yaml

from automedia.cli.output import OutputMode, get_output_mode, output_error, output_text
from automedia.core.paths import get_user_config_dir

_USER_CFG_DIR = get_user_config_dir()
_MODEL_CONFIG_FILE = _USER_CFG_DIR / "model_config.yaml"
_MANIFESTS_DIR = Path(__file__).resolve().parent.parent.parent / "manifests"

# Inline comments for generated model_config.yaml keys.
# Drawn from automedia/manifests/defaults.yaml for reference.
_TEXT_GENERATION_COMMENTS: dict[str, str] = {
    "provider": "LLM provider (openai, deepseek, anthropic, etc.)",
    "model": "Model name (e.g., gpt-4o-mini, deepseek-chat, claude-3-sonnet-20240229)",
    "api_key": "API key for the selected provider",
    "base_url": "Custom API base URL (empty = provider default)",
    "temperature": "Sampling temperature (0.0–2.0, default: 0.7)",
    "max_tokens": "Maximum tokens per response (default: 2048)",
    "timeout": "Request timeout in seconds (default: 60)",
}


def _yaml_value(val: object) -> str:
    """Serialize a scalar Python value as a YAML inline literal."""
    if val is None:
        return "null"
    if isinstance(val, bool):
        return "true" if val else "false"
    if isinstance(val, (int, float)):
        return str(val)
    s = str(val)
    if not s:
        return "''"
    if any(c in s for c in ":,[]{}&*!|>?'\"%@`"):
        import json as _json
        return _json.dumps(s, ensure_ascii=False)
    return s


def _write_model_config(data: dict) -> None:
    """Write a YAML file to ``~/.automedia/model_config.yaml``.

    When *data* follows the ``llm.text_generation`` structure the output
    includes inline comments explaining each key.  Generic dicts are
    written with plain ``yaml.dump`` for backward compatibility.
    """
    _USER_CFG_DIR.mkdir(parents=True, exist_ok=True)

    tg = data.get("llm", {}).get("text_generation", {})
    if tg:
        lines: list[str] = [
            "# AutoMedia LLM configuration",
            "# Generated by `automedia init`",
            "# Replace the values below with your own API credentials.",
            "",
            "llm:",
            "  text_generation:",
        ]
        for key in ("provider", "model", "api_key", "base_url"):
            if key in tg:
                comment = _TEXT_GENERATION_COMMENTS.get(key)
                if comment:
                    lines.append(f"    # {comment}")
                lines.append(f"    {key}: {_yaml_value(tg[key])}")
        content = "\n".join(lines) + "\n"
    else:
        content = yaml.dump(data, allow_unicode=True, default_flow_style=False, sort_keys=False)

    with open(_MODEL_CONFIG_FILE, "w", encoding="utf-8") as fh:
        fh.write(content)
    os.chmod(_MODEL_CONFIG_FILE, 0o600)
    typer.secho(f"\nConfiguration written to {_MODEL_CONFIG_FILE}", fg=typer.colors.GREEN)


def init_cmd(
    template: str | None = typer.Option(
        None,
        "--template",
        help="Non-interactive template mode (e.g. 'minimal').",
    ),
    omni: bool = typer.Option(
        False,
        "--omni",
        help="Initialize Omni Triad configuration interactively.",
    ),
) -> None:
    """Initialize AutoMedia configuration.

    Without ``--template`` runs an interactive wizard that writes
    ``~/.automedia/model_config.yaml``.

    With ``--template minimal`` generates a minimal non-interactive config
    in the same location.

    With ``--omni`` runs the Omni Triad interactive configuration wizard.
    """
    if omni:
        _init_omni()
    elif template == "minimal":
        _init_minimal()
    elif template is None:
        if get_output_mode() == OutputMode.JSON:
            output_error("Interactive init not supported in --json mode. Use --template minimal.")
        _init_interactive()
    else:
        output_error(f"Unknown template: {template!r}")


def _init_interactive() -> None:
    """Interactive configuration wizard."""
    typer.echo("AutoMedia Configuration Wizard")
    typer.echo("=" * 40)

    provider = typer.prompt("LLM provider", default="openai")
    model = typer.prompt("Model", default="gpt-4o-mini")
    api_key = typer.prompt("API key", hide_input=True)
    base_url = typer.prompt("API base URL (leave blank for default)", default="")

    data = {
        "llm": {
            "text_generation": {
                "provider": provider,
                "model": model,
                "api_key": api_key,
            },
        },
    }
    if base_url:
        data["llm"]["text_generation"]["base_url"] = base_url

    _write_model_config(data)


def _init_minimal() -> None:
    """Non-interactive minimal config generation."""
    data = {
        "llm": {
            "text_generation": {
                "provider": "openai",
                "model": "gpt-4o-mini",
                "api_key": "",
            },
        },
    }
    _write_model_config(data)
    output_text(
        "Minimal configuration written. Run `automedia doctor` to verify, then `automedia run --topic \"...\" --brand my-brand` to start.",
        data={"status": "ok", "path": str(_MODEL_CONFIG_FILE)},
    )


def _init_omni() -> None:
    """Interactive Omni Triad configuration wizard.

    Creates ``~/.automedia/omni_config.yaml``, copies template allowlist and
    localizer config files, and prompts the user for key settings.
    """
    # Check that all required template paths exist before proceeding.
    _required_templates = [
        _MANIFESTS_DIR / "omni_allowlist_template.yaml",
        _MANIFESTS_DIR / "ol_config_template.yaml",
        _MANIFESTS_DIR / "omni_config_template.yaml",
    ]
    missing = [str(p) for p in _required_templates if not p.exists()]
    if missing:
        output_error(
            "Error: The following required template file(s) were not found:\n"
            + "\n".join(f"  • {m}" for m in missing)
        )

    _USER_CFG_DIR.mkdir(parents=True, exist_ok=True)

    shutil.copy2(
        _MANIFESTS_DIR / "omni_allowlist_template.yaml",
        _USER_CFG_DIR / "omni_allowlist.yaml",
    )
    ol_dir = _USER_CFG_DIR / "omni"
    ol_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(
        _MANIFESTS_DIR / "ol_config_template.yaml",
        ol_dir / "ol_config.yaml",
    )

    integration_mode = typer.prompt("Integration mode", default="proxy", type=str)
    max_auto_extract_mb = typer.prompt("Max auto-extract (MB)", default=50, type=int)

    omni_config_path = _USER_CFG_DIR / "omni_config.yaml"
    with open(_MANIFESTS_DIR / "omni_config_template.yaml", encoding="utf-8") as fh:
        config = yaml.safe_load(fh)

    config["integration_mode"] = integration_mode
    config["max_auto_extract_mb"] = max_auto_extract_mb

    with open(omni_config_path, "w", encoding="utf-8") as fh:
        yaml.dump(config, fh, allow_unicode=True, default_flow_style=False, sort_keys=False)

    if output_text(
        None,
        data={
            "status": "ok",
            "config_dir": str(_USER_CFG_DIR),
            "files": [
                "omni_config.yaml",
                "omni_allowlist.yaml",
                "omni/ol_config.yaml",
            ],
        },
    ):
        return

    typer.secho(f"\nOmni configuration written to {_USER_CFG_DIR}", fg=typer.colors.GREEN)
    typer.secho("  └─ omni_config.yaml", fg=typer.colors.GREEN)
    typer.secho("  └─ omni_allowlist.yaml", fg=typer.colors.GREEN)
    typer.secho("  └─ omni/ol_config.yaml", fg=typer.colors.GREEN)
